### ISSUE TITLE
Trying to implement the universal swap from token script

### ISSUE THREAD

**Issue by cgx-ai** [0xMaka/w3py#1]
I am gettting reverted right on the first line of the i swap router 

At first I thought I had typed something incorrectly but then I just copied and pasted the entire script and got the same revert right in the first line of the ISwapRouter contract. I still probably did something wrong but even when I copied and pasted the script I got the same error as with my own version

I posted a question about it on stack here with all the info
[Link to stack question](https://ethereum.stackexchange.com/q/163924/133953)

**Comment by 0xMaka** [comment]
Hey thank you so much, the example is using the WETH address from Polygon rather than the WETH address from base. Have corrected.
